### ISSUE TITLE
libflac compiling help

### ISSUE THREAD

**Issue by deltabeard** [machinamentum/music_player#1]
Hello,

I was wondering how you were able to compile libflac and if you would be so kind to provide some instructions? I keep receiving compiler errors and was wondering if you could help since you have a working build.

Thanks, and great work on creating the only flac player on the 3ds.

**Comment by machinamentum** [comment]
Sorry for the late response. I dont have an original copy of what I was using back when I worked on this.
To build from source, download the lated libogg and libFLAC from their respective websites. Add $DEVKITPRO/devkitARM/bin to your system path so that you can run arm-none-eabi-gcc from terminal. Then from libogg's source directory run
```
./configure --prefix=$DEVKITPRO//libctru --host=arm-none-eabi --disable-shared --enable-static
make
make install
```
From llibFLAC's source directory run the same commands
```
./configure --prefix=$DEVKITPRO//libctru --host=arm-none-eabi --disable-shared --enable-static
make
make install
```
This should produce a working copy. I can't test if they compile/link correctly with music_player still since I dont have Caelina currently installed on my computer.

**Comment by deltabeard** [comment]
Thanks for the reply. I tried to add libFLAC to [3ds-portlibs](https://github.com/devkitPro/3ds_portlibs) and then compiling it, but that didn't work either. I believe the commands that 3ds-portlibs use are the same that you stated in your reply.

Anyways, I managed to find an alternative flac decoder library in [dr_libs](https://github.com/mackron/dr_libs) which compiles and works fine. But thanks anyway. :+1:
